name: GitHub Pages

on:
  push:
    branches:
      - main
  #pull_request:

jobs:
  deploy:
    runs-on: 
      - self-hosted
      - linux/amd64
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v6
      - name: Build
        run: |
          pip install pdoc3 httpx attrs
          pdoc --html --output-dir tmp --force python_odpt/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./tmp/python_odpt
